#!/bin/bash

# 从标准输入读取推送内容
while read oldrev newrev refname; do
  branch=$(git rev-parse --symbolic --abbrev-ref "$refname")

  # 使用正则表达式校验分支名称
  if [[ ! $branch =~ ^(version|hotfix)/[[:alnum:]]+ ]]; then
    echo "错误: 分支名称不符合要求"
    exit 1
  fi
done

exit 0